name: Deploy GEE-enabled site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GEE directory
        run: |
          mkdir -p $HOME/.config/earthengine

      - name: Authenticate with GEE
        run: |
          npm install @google/earthengine-api
          echo ${{ secrets.API_KEY }} > $HOME/.config/earthengine/credentials

      - name: Build
        run: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public